// !!! This file is generated by emlearn !!!

    #include <eml_bayes.h>


EmlBayesSummary occupancy_model_summaries[4] = {
        { EML_Q16_FROMFLOAT(20.44429353894629),EML_Q16_FROMFLOAT(0.8782541068876558),EML_Q16_FROMFLOAT(-0.1872896771002893) },
        { EML_Q16_FROMFLOAT(502.86696755844804),EML_Q16_FROMFLOAT(154.9958612070166),EML_Q16_FROMFLOAT(7.276085882075318) },
        { EML_Q16_FROMFLOAT(21.920075180728997),EML_Q16_FROMFLOAT(0.8428764695775521),EML_Q16_FROMFLOAT(-0.24660688695462415) },
        { EML_Q16_FROMFLOAT(1028.3925676230738),EML_Q16_FROMFLOAT(334.71768356744457),EML_Q16_FROMFLOAT(8.38680096225459) }
    };


EmlBayesModel occupancy_model_model = {
        2,
        2,
        occupancy_model_summaries,
    };



    int32_t
    occupancy_model_predict(const float *features, int32_t n_features)
    {
        return eml_bayes_predict(&occupancy_model_model, features, n_features);

    }
    